### PR TITLE
More FOSDEM 2016

### PR DESCRIPTION
**Pull request by clacke**

### CODE REVIEW

**Comment by RichiH** [comment]
Thanks!

**Comment by RichiH** [comment]
@clacke I am considering to just give you commit access to this repo. Interested?

**Comment by joeyh** [comment]
Getting checksum errors downloading some of these. This is why it's better to addurl with --relaxed for such videos.

**Comment by RichiH** [comment]
Meh.

Is there a canonical way to fix ALL the things?

**Comment by joeyh** [comment]
Richard Hartmann wrote:
> Meh.
> 
> Is there a canonical way to fix ALL the things?

Short of re-importing, I don't have one handy.

-- 
see shy jo

**Pull request merged**
